name: Package Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract Version from JS
        id: get_version
        run: |
          # @version pull
          VERSION=$(grep "@version" "Gaijin Store Partner HUD.js" | awk '{print $3}' | tr -d '\r\n')
          
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from JS file!"
            exit 1
          fi
          
          echo "Extracted Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT


      - name: Create manifest.json
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          
          cat <<EOF > manifest.json
          {
            "manifest_version": 3,
            "name": "Gaijin Store Partner HUD",
            "version": "$VERSION",
            "description": "WTPB Reminder HUD for the Gaijin Store.",
            "author": "SempiternalSloth",
            "permissions": ["storage"],
            "content_scripts": [
              {
                "matches": ["https://store.gaijin.net/*"],
                "js": ["Gaijin Store Partner HUD.js"],
                "run_at": "document_end"
              }
            ],
            "icons": {
              "48": "gaijinreminderwtpb.png"
            }
          }
          EOF
          
      - name: Zip extension assets
        run: |
          zip -r "Gaijin-Store-Partner-HUD.zip" "manifest.json" "Gaijin Store Partner HUD.js" "gaijinreminderwtpb.png"


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: Gaijin-Store-Partner-HUD.zip
